# Generated by Django 5.2.16 on 2026-08-02 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farm_area_acres', models.FloatField()),
                ('crop_type', models.CharField(max_length=100)),
                ('soil_type', models.CharField(default='Clay Loam', max_length=100)),
                ('current_moisture_percent', models.FloatField()),
                ('recommended_water_liters_per_acre', models.FloatField()),
                ('total_water_liters', models.FloatField()),
                ('recommended_time_window', models.CharField(max_length=255)),
                ('irrigation_frequency_days', models.IntegerField(default=2)),
                ('next_scheduled_date', models.DateField()),
                ('weather_adjustments', models.TextField()),
                ('moisture_deficit_percent', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
