# Generated by Django 5.2.16 on 2026-08-02 10:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecommendationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nitrogen', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('phosphorus', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('potassium', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ph', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('rainfall', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('recommended_crop', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('expected_yield_tons_per_acre', models.FloatField()),
                ('estimated_profit_usd_per_acre', models.FloatField()),
                ('alternative_crops', models.JSONField(default=list)),
                ('explainable_ai', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
