# Generated by Django 5.2.16 on 2026-08-02 09:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('total_area_hectares', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('current_crop', models.CharField(blank=True, max_length=150, null=True)),
                ('soil_type', models.CharField(choices=[('CLAY', 'Clay Soil'), ('SANDY', 'Sandy Soil'), ('LOAM', 'Loam Soil'), ('SILT', 'Silt Soil'), ('PEAT', 'Peat Soil'), ('CHALKY', 'Chalky Soil')], default='LOAM', max_length=50)),
                ('irrigation_type', models.CharField(choices=[('DRIP', 'Drip Irrigation'), ('SPRINKLER', 'Sprinkler System'), ('CENTER_PIVOT', 'Center Pivot'), ('FLOOD', 'Flood/Surface Irrigation'), ('RAINFED', 'Rainfed / Natural')], default='DRIP', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Cultivation'), ('FALLOW', 'Fallow / Resting'), ('PREPARATION', 'Land Preparation'), ('HARVESTED', 'Harvested')], default='ACTIVE', max_length=50)),
                ('boundary_coordinates', models.JSONField(blank=True, default=dict, help_text='Polygon JSON coordinates defining field geographical boundary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='farms.farm')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CropHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=150)),
                ('variety', models.CharField(blank=True, max_length=150, null=True)),
                ('planting_date', models.DateField()),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('yield_tonnes_per_hectare', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_histories', to='farms.field')),
            ],
            options={
                'ordering': ['-planting_date'],
            },
        ),
        migrations.CreateModel(
            name='SoilRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sampled_at', models.DateField(db_index=True)),
                ('ph_level', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)])),
                ('nitrogen_mg_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('phosphorus_mg_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('potassium_mg_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('organic_matter_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('moisture_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('electrical_conductivity', models.DecimalField(decimal_places=2, default=0.0, help_text='dS/m', max_digits=6)),
                ('health_score', models.IntegerField(default=85, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_records', to='farms.field')),
            ],
            options={
                'ordering': ['-sampled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['owner', 'is_active'], name='farms_farm_owner_i_244c09_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['latitude', 'longitude'], name='farms_farm_latitud_f76213_idx'),
        ),
    ]
