# Generated by Django 5.2.16 on 2026-08-02 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropCommodityPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(db_index=True, max_length=150)),
                ('market_location', models.CharField(max_length=255)),
                ('current_price_usd_per_ton', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_percentage', models.FloatField()),
                ('demand_level', models.CharField(default='High', max_length=50)),
                ('forecasted_30d_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_history', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['crop_name'],
            },
        ),
    ]
