# Generated by Django 5.2.16 on 2026-08-02 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_name', models.CharField(db_index=True, max_length=255)),
                ('alert_type', models.CharField(choices=[('FROST', 'Frost Warning'), ('RAIN', 'Heavy Rainfall Risk'), ('HEAT', 'Extreme Thermal Stress'), ('WIND', 'High Wind Hazard'), ('PEST', 'Pest Outbreak Climate Risk')], max_length=50)),
                ('headline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(default='Moderate', max_length=50)),
                ('action_required', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
